/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias/index'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas/index'
import { Route as ArtigosIndexRouteImport } from './routes/artigos/index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias/$slug'
import { Route as FerramentasUuidRouteImport } from './routes/ferramentas/uuid'
import { Route as FerramentasUtmBuilderRouteImport } from './routes/ferramentas/utm-builder'
import { Route as FerramentasTranslatorRouteImport } from './routes/ferramentas/translator'
import { Route as FerramentasSummarizerRouteImport } from './routes/ferramentas/summarizer'
import { Route as FerramentasSitemapRouteImport } from './routes/ferramentas/sitemap'
import { Route as FerramentasSchemaRouteImport } from './routes/ferramentas/schema'
import { Route as FerramentasRobotsRouteImport } from './routes/ferramentas/robots'
import { Route as FerramentasRewriterRouteImport } from './routes/ferramentas/rewriter'
import { Route as FerramentasQrCodeGeneratorRouteImport } from './routes/ferramentas/qr-code-generator'
import { Route as FerramentasPromptGeneratorRouteImport } from './routes/ferramentas/prompt-generator'
import { Route as FerramentasPixelHelperRouteImport } from './routes/ferramentas/pixel-helper'
import { Route as FerramentasOpenGraphRouteImport } from './routes/ferramentas/open-graph'
import { Route as FerramentasMetaTagsRouteImport } from './routes/ferramentas/meta-tags'
import { Route as FerramentasKeywordDensityRouteImport } from './routes/ferramentas/keyword-density'
import { Route as FerramentasJsonFormatterRouteImport } from './routes/ferramentas/json-formatter'
import { Route as FerramentasHashRouteImport } from './routes/ferramentas/hash'
import { Route as FerramentasColorPickerRouteImport } from './routes/ferramentas/color-picker'
import { Route as FerramentasCanonicalRouteImport } from './routes/ferramentas/canonical'
import { Route as FerramentasBase64RouteImport } from './routes/ferramentas/base64'
import { Route as FerramentasSlugRouteImport } from './routes/ferramentas/$slug'
import { Route as CategoriasCategoriaRouteImport } from './routes/categorias/$categoria'
import { Route as ArtigosSlugRouteImport } from './routes/artigos/$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasUuidRoute = FerramentasUuidRouteImport.update({
  id: '/uuid',
  path: '/uuid',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasUtmBuilderRoute = FerramentasUtmBuilderRouteImport.update({
  id: '/utm-builder',
  path: '/utm-builder',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasTranslatorRoute = FerramentasTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasSummarizerRoute = FerramentasSummarizerRouteImport.update({
  id: '/summarizer',
  path: '/summarizer',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasSitemapRoute = FerramentasSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasSchemaRoute = FerramentasSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasRobotsRoute = FerramentasRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasRewriterRoute = FerramentasRewriterRouteImport.update({
  id: '/rewriter',
  path: '/rewriter',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasQrCodeGeneratorRoute =
  FerramentasQrCodeGeneratorRouteImport.update({
    id: '/qr-code-generator',
    path: '/qr-code-generator',
    getParentRoute: () => FerramentasRoute,
  } as any)
const FerramentasPromptGeneratorRoute =
  FerramentasPromptGeneratorRouteImport.update({
    id: '/prompt-generator',
    path: '/prompt-generator',
    getParentRoute: () => FerramentasRoute,
  } as any)
const FerramentasPixelHelperRoute = FerramentasPixelHelperRouteImport.update({
  id: '/pixel-helper',
  path: '/pixel-helper',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasOpenGraphRoute = FerramentasOpenGraphRouteImport.update({
  id: '/open-graph',
  path: '/open-graph',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasMetaTagsRoute = FerramentasMetaTagsRouteImport.update({
  id: '/meta-tags',
  path: '/meta-tags',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasKeywordDensityRoute =
  FerramentasKeywordDensityRouteImport.update({
    id: '/keyword-density',
    path: '/keyword-density',
    getParentRoute: () => FerramentasRoute,
  } as any)
const FerramentasJsonFormatterRoute =
  FerramentasJsonFormatterRouteImport.update({
    id: '/json-formatter',
    path: '/json-formatter',
    getParentRoute: () => FerramentasRoute,
  } as any)
const FerramentasHashRoute = FerramentasHashRouteImport.update({
  id: '/hash',
  path: '/hash',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasColorPickerRoute = FerramentasColorPickerRouteImport.update({
  id: '/color-picker',
  path: '/color-picker',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasCanonicalRoute = FerramentasCanonicalRouteImport.update({
  id: '/canonical',
  path: '/canonical',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasBase64Route = FerramentasBase64RouteImport.update({
  id: '/base64',
  path: '/base64',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasSlugRoute = FerramentasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FerramentasRoute,
} as any)
const CategoriasCategoriaRoute = CategoriasCategoriaRouteImport.update({
  id: '/categorias/$categoria',
  path: '/categorias/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/ferramentas/$slug': typeof FerramentasSlugRoute
  '/ferramentas/base64': typeof FerramentasBase64Route
  '/ferramentas/canonical': typeof FerramentasCanonicalRoute
  '/ferramentas/color-picker': typeof FerramentasColorPickerRoute
  '/ferramentas/hash': typeof FerramentasHashRoute
  '/ferramentas/json-formatter': typeof FerramentasJsonFormatterRoute
  '/ferramentas/keyword-density': typeof FerramentasKeywordDensityRoute
  '/ferramentas/meta-tags': typeof FerramentasMetaTagsRoute
  '/ferramentas/open-graph': typeof FerramentasOpenGraphRoute
  '/ferramentas/pixel-helper': typeof FerramentasPixelHelperRoute
  '/ferramentas/prompt-generator': typeof FerramentasPromptGeneratorRoute
  '/ferramentas/qr-code-generator': typeof FerramentasQrCodeGeneratorRoute
  '/ferramentas/rewriter': typeof FerramentasRewriterRoute
  '/ferramentas/robots': typeof FerramentasRobotsRoute
  '/ferramentas/schema': typeof FerramentasSchemaRoute
  '/ferramentas/sitemap': typeof FerramentasSitemapRoute
  '/ferramentas/summarizer': typeof FerramentasSummarizerRoute
  '/ferramentas/translator': typeof FerramentasTranslatorRoute
  '/ferramentas/utm-builder': typeof FerramentasUtmBuilderRoute
  '/ferramentas/uuid': typeof FerramentasUuidRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/ferramentas/$slug': typeof FerramentasSlugRoute
  '/ferramentas/base64': typeof FerramentasBase64Route
  '/ferramentas/canonical': typeof FerramentasCanonicalRoute
  '/ferramentas/color-picker': typeof FerramentasColorPickerRoute
  '/ferramentas/hash': typeof FerramentasHashRoute
  '/ferramentas/json-formatter': typeof FerramentasJsonFormatterRoute
  '/ferramentas/keyword-density': typeof FerramentasKeywordDensityRoute
  '/ferramentas/meta-tags': typeof FerramentasMetaTagsRoute
  '/ferramentas/open-graph': typeof FerramentasOpenGraphRoute
  '/ferramentas/pixel-helper': typeof FerramentasPixelHelperRoute
  '/ferramentas/prompt-generator': typeof FerramentasPromptGeneratorRoute
  '/ferramentas/qr-code-generator': typeof FerramentasQrCodeGeneratorRoute
  '/ferramentas/rewriter': typeof FerramentasRewriterRoute
  '/ferramentas/robots': typeof FerramentasRobotsRoute
  '/ferramentas/schema': typeof FerramentasSchemaRoute
  '/ferramentas/sitemap': typeof FerramentasSitemapRoute
  '/ferramentas/summarizer': typeof FerramentasSummarizerRoute
  '/ferramentas/translator': typeof FerramentasTranslatorRoute
  '/ferramentas/utm-builder': typeof FerramentasUtmBuilderRoute
  '/ferramentas/uuid': typeof FerramentasUuidRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artigos': typeof ArtigosIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/categorias/$categoria': typeof CategoriasCategoriaRoute
  '/ferramentas/$slug': typeof FerramentasSlugRoute
  '/ferramentas/base64': typeof FerramentasBase64Route
  '/ferramentas/canonical': typeof FerramentasCanonicalRoute
  '/ferramentas/color-picker': typeof FerramentasColorPickerRoute
  '/ferramentas/hash': typeof FerramentasHashRoute
  '/ferramentas/json-formatter': typeof FerramentasJsonFormatterRoute
  '/ferramentas/keyword-density': typeof FerramentasKeywordDensityRoute
  '/ferramentas/meta-tags': typeof FerramentasMetaTagsRoute
  '/ferramentas/open-graph': typeof FerramentasOpenGraphRoute
  '/ferramentas/pixel-helper': typeof FerramentasPixelHelperRoute
  '/ferramentas/prompt-generator': typeof FerramentasPromptGeneratorRoute
  '/ferramentas/qr-code-generator': typeof FerramentasQrCodeGeneratorRoute
  '/ferramentas/rewriter': typeof FerramentasRewriterRoute
  '/ferramentas/robots': typeof FerramentasRobotsRoute
  '/ferramentas/schema': typeof FerramentasSchemaRoute
  '/ferramentas/sitemap': typeof FerramentasSitemapRoute
  '/ferramentas/summarizer': typeof FerramentasSummarizerRoute
  '/ferramentas/translator': typeof FerramentasTranslatorRoute
  '/ferramentas/utm-builder': typeof FerramentasUtmBuilderRoute
  '/ferramentas/uuid': typeof FerramentasUuidRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/ferramentas'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/artigos/$slug'
    | '/categorias/$categoria'
    | '/ferramentas/$slug'
    | '/ferramentas/base64'
    | '/ferramentas/canonical'
    | '/ferramentas/color-picker'
    | '/ferramentas/hash'
    | '/ferramentas/json-formatter'
    | '/ferramentas/keyword-density'
    | '/ferramentas/meta-tags'
    | '/ferramentas/open-graph'
    | '/ferramentas/pixel-helper'
    | '/ferramentas/prompt-generator'
    | '/ferramentas/qr-code-generator'
    | '/ferramentas/rewriter'
    | '/ferramentas/robots'
    | '/ferramentas/schema'
    | '/ferramentas/sitemap'
    | '/ferramentas/summarizer'
    | '/ferramentas/translator'
    | '/ferramentas/utm-builder'
    | '/ferramentas/uuid'
    | '/noticias/$slug'
    | '/artigos/'
    | '/ferramentas/'
    | '/noticias/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/artigos/$slug'
    | '/categorias/$categoria'
    | '/ferramentas/$slug'
    | '/ferramentas/base64'
    | '/ferramentas/canonical'
    | '/ferramentas/color-picker'
    | '/ferramentas/hash'
    | '/ferramentas/json-formatter'
    | '/ferramentas/keyword-density'
    | '/ferramentas/meta-tags'
    | '/ferramentas/open-graph'
    | '/ferramentas/pixel-helper'
    | '/ferramentas/prompt-generator'
    | '/ferramentas/qr-code-generator'
    | '/ferramentas/rewriter'
    | '/ferramentas/robots'
    | '/ferramentas/schema'
    | '/ferramentas/sitemap'
    | '/ferramentas/summarizer'
    | '/ferramentas/translator'
    | '/ferramentas/utm-builder'
    | '/ferramentas/uuid'
    | '/noticias/$slug'
    | '/artigos'
    | '/ferramentas'
    | '/noticias'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/ferramentas'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/artigos/$slug'
    | '/categorias/$categoria'
    | '/ferramentas/$slug'
    | '/ferramentas/base64'
    | '/ferramentas/canonical'
    | '/ferramentas/color-picker'
    | '/ferramentas/hash'
    | '/ferramentas/json-formatter'
    | '/ferramentas/keyword-density'
    | '/ferramentas/meta-tags'
    | '/ferramentas/open-graph'
    | '/ferramentas/pixel-helper'
    | '/ferramentas/prompt-generator'
    | '/ferramentas/qr-code-generator'
    | '/ferramentas/rewriter'
    | '/ferramentas/robots'
    | '/ferramentas/schema'
    | '/ferramentas/sitemap'
    | '/ferramentas/summarizer'
    | '/ferramentas/translator'
    | '/ferramentas/utm-builder'
    | '/ferramentas/uuid'
    | '/noticias/$slug'
    | '/artigos/'
    | '/ferramentas/'
    | '/noticias/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  FerramentasRoute: typeof FerramentasRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  CategoriasCategoriaRoute: typeof CategoriasCategoriaRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/uuid': {
      id: '/ferramentas/uuid'
      path: '/uuid'
      fullPath: '/ferramentas/uuid'
      preLoaderRoute: typeof FerramentasUuidRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/utm-builder': {
      id: '/ferramentas/utm-builder'
      path: '/utm-builder'
      fullPath: '/ferramentas/utm-builder'
      preLoaderRoute: typeof FerramentasUtmBuilderRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/translator': {
      id: '/ferramentas/translator'
      path: '/translator'
      fullPath: '/ferramentas/translator'
      preLoaderRoute: typeof FerramentasTranslatorRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/summarizer': {
      id: '/ferramentas/summarizer'
      path: '/summarizer'
      fullPath: '/ferramentas/summarizer'
      preLoaderRoute: typeof FerramentasSummarizerRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/sitemap': {
      id: '/ferramentas/sitemap'
      path: '/sitemap'
      fullPath: '/ferramentas/sitemap'
      preLoaderRoute: typeof FerramentasSitemapRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/schema': {
      id: '/ferramentas/schema'
      path: '/schema'
      fullPath: '/ferramentas/schema'
      preLoaderRoute: typeof FerramentasSchemaRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/robots': {
      id: '/ferramentas/robots'
      path: '/robots'
      fullPath: '/ferramentas/robots'
      preLoaderRoute: typeof FerramentasRobotsRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/rewriter': {
      id: '/ferramentas/rewriter'
      path: '/rewriter'
      fullPath: '/ferramentas/rewriter'
      preLoaderRoute: typeof FerramentasRewriterRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/qr-code-generator': {
      id: '/ferramentas/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/ferramentas/qr-code-generator'
      preLoaderRoute: typeof FerramentasQrCodeGeneratorRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/prompt-generator': {
      id: '/ferramentas/prompt-generator'
      path: '/prompt-generator'
      fullPath: '/ferramentas/prompt-generator'
      preLoaderRoute: typeof FerramentasPromptGeneratorRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/pixel-helper': {
      id: '/ferramentas/pixel-helper'
      path: '/pixel-helper'
      fullPath: '/ferramentas/pixel-helper'
      preLoaderRoute: typeof FerramentasPixelHelperRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/open-graph': {
      id: '/ferramentas/open-graph'
      path: '/open-graph'
      fullPath: '/ferramentas/open-graph'
      preLoaderRoute: typeof FerramentasOpenGraphRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/meta-tags': {
      id: '/ferramentas/meta-tags'
      path: '/meta-tags'
      fullPath: '/ferramentas/meta-tags'
      preLoaderRoute: typeof FerramentasMetaTagsRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/keyword-density': {
      id: '/ferramentas/keyword-density'
      path: '/keyword-density'
      fullPath: '/ferramentas/keyword-density'
      preLoaderRoute: typeof FerramentasKeywordDensityRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/json-formatter': {
      id: '/ferramentas/json-formatter'
      path: '/json-formatter'
      fullPath: '/ferramentas/json-formatter'
      preLoaderRoute: typeof FerramentasJsonFormatterRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/hash': {
      id: '/ferramentas/hash'
      path: '/hash'
      fullPath: '/ferramentas/hash'
      preLoaderRoute: typeof FerramentasHashRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/color-picker': {
      id: '/ferramentas/color-picker'
      path: '/color-picker'
      fullPath: '/ferramentas/color-picker'
      preLoaderRoute: typeof FerramentasColorPickerRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/canonical': {
      id: '/ferramentas/canonical'
      path: '/canonical'
      fullPath: '/ferramentas/canonical'
      preLoaderRoute: typeof FerramentasCanonicalRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/base64': {
      id: '/ferramentas/base64'
      path: '/base64'
      fullPath: '/ferramentas/base64'
      preLoaderRoute: typeof FerramentasBase64RouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/$slug': {
      id: '/ferramentas/$slug'
      path: '/$slug'
      fullPath: '/ferramentas/$slug'
      preLoaderRoute: typeof FerramentasSlugRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/categorias/$categoria': {
      id: '/categorias/$categoria'
      path: '/categorias/$categoria'
      fullPath: '/categorias/$categoria'
      preLoaderRoute: typeof CategoriasCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FerramentasRouteChildren {
  FerramentasSlugRoute: typeof FerramentasSlugRoute
  FerramentasBase64Route: typeof FerramentasBase64Route
  FerramentasCanonicalRoute: typeof FerramentasCanonicalRoute
  FerramentasColorPickerRoute: typeof FerramentasColorPickerRoute
  FerramentasHashRoute: typeof FerramentasHashRoute
  FerramentasJsonFormatterRoute: typeof FerramentasJsonFormatterRoute
  FerramentasKeywordDensityRoute: typeof FerramentasKeywordDensityRoute
  FerramentasMetaTagsRoute: typeof FerramentasMetaTagsRoute
  FerramentasOpenGraphRoute: typeof FerramentasOpenGraphRoute
  FerramentasPixelHelperRoute: typeof FerramentasPixelHelperRoute
  FerramentasPromptGeneratorRoute: typeof FerramentasPromptGeneratorRoute
  FerramentasQrCodeGeneratorRoute: typeof FerramentasQrCodeGeneratorRoute
  FerramentasRewriterRoute: typeof FerramentasRewriterRoute
  FerramentasRobotsRoute: typeof FerramentasRobotsRoute
  FerramentasSchemaRoute: typeof FerramentasSchemaRoute
  FerramentasSitemapRoute: typeof FerramentasSitemapRoute
  FerramentasSummarizerRoute: typeof FerramentasSummarizerRoute
  FerramentasTranslatorRoute: typeof FerramentasTranslatorRoute
  FerramentasUtmBuilderRoute: typeof FerramentasUtmBuilderRoute
  FerramentasUuidRoute: typeof FerramentasUuidRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasSlugRoute: FerramentasSlugRoute,
  FerramentasBase64Route: FerramentasBase64Route,
  FerramentasCanonicalRoute: FerramentasCanonicalRoute,
  FerramentasColorPickerRoute: FerramentasColorPickerRoute,
  FerramentasHashRoute: FerramentasHashRoute,
  FerramentasJsonFormatterRoute: FerramentasJsonFormatterRoute,
  FerramentasKeywordDensityRoute: FerramentasKeywordDensityRoute,
  FerramentasMetaTagsRoute: FerramentasMetaTagsRoute,
  FerramentasOpenGraphRoute: FerramentasOpenGraphRoute,
  FerramentasPixelHelperRoute: FerramentasPixelHelperRoute,
  FerramentasPromptGeneratorRoute: FerramentasPromptGeneratorRoute,
  FerramentasQrCodeGeneratorRoute: FerramentasQrCodeGeneratorRoute,
  FerramentasRewriterRoute: FerramentasRewriterRoute,
  FerramentasRobotsRoute: FerramentasRobotsRoute,
  FerramentasSchemaRoute: FerramentasSchemaRoute,
  FerramentasSitemapRoute: FerramentasSitemapRoute,
  FerramentasSummarizerRoute: FerramentasSummarizerRoute,
  FerramentasTranslatorRoute: FerramentasTranslatorRoute,
  FerramentasUtmBuilderRoute: FerramentasUtmBuilderRoute,
  FerramentasUuidRoute: FerramentasUuidRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  FerramentasRoute: FerramentasRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  CategoriasCategoriaRoute: CategoriasCategoriaRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
