CREATE TABLE `news` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`summary` text,
	`content` text NOT NULL,
	`coverImage` varchar(512),
	`coverImageAlt` varchar(255),
	`category` enum('ia','engenharia','seguranca','cloud','dados','carreira') NOT NULL,
	`categorySlug` varchar(64) NOT NULL,
	`tags` text,
	`author` varchar(255) NOT NULL,
	`status` enum('draft','published','scheduled','archived') DEFAULT 'draft',
	`featured` int DEFAULT 0,
	`breaking` int DEFAULT 0,
	`pinned` int DEFAULT 0,
	`priority` int DEFAULT 0,
	`views` int DEFAULT 0,
	`viewsLast7Days` int DEFAULT 0,
	`readingTime` int,
	`seoTitle` varchar(255),
	`seoDescription` varchar(512),
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `news_id` PRIMARY KEY(`id`),
	CONSTRAINT `news_slug_unique` UNIQUE(`slug`)
);
